name:                multi-targeter
version:             0.1.0.0
github:              "GetUp/multi-targeter"
license:             BSD3
author:              "GetUp Tech"
maintainer:          "tim@getup.org.au"
copyright:           "GetUp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/getup/multi-targeter#readme>

dependencies:
- base >= 4.7 && < 5
- serverless-haskell
- lens
- bytestring
- unordered-containers
- text
- aeson
- xml-conduit-writer
- xml-conduit
- postgresql-simple
- http-types

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  multi-targeter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Werror
    dependencies:
    - multi-targeter

tests:
  multi-targeter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - multi-targeter
    - hspec
    - aeson
    - http-types
