service: multi-targeter

provider:
  name: aws
  runtime: haskell

functions:
  multiTargeter:
    handler: multi-targeter.multi-targeter-exe
    events:
      - http:
          integration: lambda-proxy
          path: endpoint/{url}
          method: ANY

plugins:
  - serverless-haskell
  - serverless-offline
